[personal]
  name = "Krithik Rao"
  contact = [
    "309-826-4765",
    "krdevmail@gmail.com",
    "linkedin.com/in/krithikr",
    "github.com/KritR",
  ]

[[blocks]]
  title = "Education"

  [[blocks.subheadings]]
    title = "Purdue University - 3.84 GPA"
    duration = "May 2018 - Dec 2020"
    notes = [
      "Bachelor's In Computer Science • Machine Learning Concentration",
    ]

[[blocks]]
  title = "Experience"

  [[blocks.subheadings]]
    title = "GE Transportation/Wabtec - Software Engineering Intern"
    duration = "May 2019 - Aug 2019"
    notes = [
      "Developed an automated test infrastructure for the Remote Control Locomotive product.",
      "Lead package manager integration initiative to ease software deployment procedure.",
      "Deployed a command line parser library in C#.",
      "Designed graphics for intern hosted professional development and fundraising events.",
    ]

[[blocks]]
  title = "Activities"

  [[blocks.subheadings]]
    title = "FIRST Robotics | Team 4213 - Software Team Lead"
    duration = "Aug 2015 - Sep 2017"
    notes = [
      "Implemented a custom scheduler and state machine for robot operations and vision processing.",
      "Architected a Laravel web application for a Sponsor Relationship Management system.",
      "Lead CAD and programming workshops for new teammates.",
    ]
